name: Python CI for Choreo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Lint code
        run: |
          flake8 .

      - name: Run tests
        run: |
          if [ -d "tests" ]; then
            pytest tests
          else
            echo "No tests directory, skipping tests"
          fi

      - name: Create deployment artifact
        run: |
          zip -r bot_deploy.zip . -x '*.git*' '*.github*' '*.env*' '*.DS_Store'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: bot_deploy
          path: bot_deploy.zip
